#项目名称
appname = "mattermost-plugin-svn"
#是否跳过ssl tls验证
verify_cert = true

[groups]
[groups.web]
# mattermost hook url 菜单->Integrations->incoming webhooks->右上角创建 要创建要指定的channel
webhookurl = "http://192.168.3.100:8065/hooks/us5wkap97ibi5no6req5qoa8cw"
# 包含的项目名
projectnames = ["web","web_exchange","web_custom"]
# 发送的所有路径  全路径 例如 D：/svn/aaa/bbb/，如果全路径匹配就直接发送，
# 就会去匹配项目名， 如果项目也没有匹配到， 就不发送。
projectpaths = [
    "",
    "",
    ""
]
#项目组成员
authors =["majianchun","wangxiao"]
#项目组 channel 需要操作界面创建 -> url上的 channels 后的名字 或者 view info 菜单
channel = "web-svn"
# 需要勾选System Console-》Integrations -》intergration management-> Enable integrations to override usernames: true
# 如果打开， 随便传入什么username 都会显示
# System Console-》Integrations -》Bot Accounts -》打开创建机器人设置 
# 此处可以是单独的人名 加上@ 比如 @majianchun 
username = "websvnbot"
[groups.server]
# mattermost hook url
webhookurl = "http://192.168.3.100:8065/hooks/imunw8dhu7bg7x3wksaa1z33ba"
# 包含的项目名
projectnames = ["server"]
# 发送的所有路径  全路径 例如 D：/svn/aaa/bbb/，如果全路径匹配就直接发送，
# 就会去匹配项目名， 如果项目也没有匹配到， 就不发送。
projectpaths = [
    "",
    "",
    ""
]
#项目组成员
authors =["xuxiaochen"]
#项目组 channel 需要操作界面创建
channel = "town-square"
#项目组 机器人名称
username = "serversvnbot"

