#项目名称
appname = "mattermost-plugin-svn"

[mattermost]
# mattermost hook url
webhookurl = "http://192.168.3.100:8065/mattermost/hooks/ay1hydt1biga5xhmua1ewrjatr"
# mattermost icon 地址 目前看似乎没有好事
iconurl =  "https://svn.apache.org/repos/asf/subversion/trunk/notes/logo/256-colour/subversion_logo-200x173.png"
# 显示的机器人名
username = "svnbot"
# 通知的channel
channel = "svnshow"

#是否跳过ssl tls验证
verify_cert = true

[groups]
[groups.web]
# 包含的项目名
projectnames = ["web","web_exchange","web_custom"]
# 发送的所有路径
projectpaths = [
    "",
    "",
    ""
]
#项目组成员
authors =["majianchun","wangxiao"]
#项目组 channel 需要操作界面创建
channel = ""
#项目组 机器人名称
username = ""
[groups.server]
# 包含的项目名
projectnames = ["server"]
# 发送的所有路径
projectpaths = [
    "",
    "",
    ""
]
#项目组成员
authors =["aaa"]
#项目组 channel 需要操作界面创建
channel = ""
#项目组 机器人名称
username = ""

