#项目名称
appname = "mattermost-plugin-svn"

[mattermost]
# mattermost hook url
webhookurl = "http://192.168.3.100:8065/mattermost/hooks/ay1hydt1biga5xhmua1ewrjatr"
# mattermost icon 地址 目前看似乎没有好事
iconurl =  "https://svn.apache.org/repos/asf/subversion/trunk/notes/logo/256-colour/subversion_logo-200x173.png"
# 显示的机器人名
username = "svnbot"
# 通知的channel
channel = "svnshow"

#是否跳过ssl tls验证
verify_cert = true

[groups]
[groups.web]
# mattermost hook url
webhookurl = "http://192.168.3.100:8065/mattermost/hooks/ay1hydt1biga5xhmua1ewrjatr"
# 包含的项目名
projectnames = ["web","web_exchange","web_custom"]
# 发送的所有路径  全路径 例如 D：/svn/aaa/bbb/，如果全路径匹配就直接发送，
# 就会去匹配项目名， 如果项目也没有匹配到， 就不发送。
projectpaths = [
    "",
    "",
    ""
]
#项目组成员
authors =["majianchun","wangxiao"]
#项目组 channel 需要操作界面创建
channel = "svnshow"
#项目组 机器人名称
username = "websvnbot"
[groups.server]
# mattermost hook url
webhookurl = "http://192.168.3.100:8065/mattermost/hooks/imunw8dhu7bg7x3wksaa1z33ba"
# 包含的项目名
projectnames = ["server"]
# 发送的所有路径  全路径 例如 D：/svn/aaa/bbb/，如果全路径匹配就直接发送，
# 就会去匹配项目名， 如果项目也没有匹配到， 就不发送。
projectpaths = [
    "",
    "",
    ""
]
#项目组成员
authors =["xuxiaochen"]
#项目组 channel 需要操作界面创建
channel = "town-square"
#项目组 机器人名称
username = "serversvnbot"

