#!/bin/sh
export LANG=en_US.UTF-8
# POST-COMMIT HOOK
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)

# *************************************************************
# * Edit the following lines to suit your environment         *
# *************************************************************
# Set full path to svnlook.exe
SVNLOOK=/usr/bin/svnlook 
# Set full path to svnplus.exe
POSTEXE=/opt/mjc/svn/golab/src/mattermost-plugin-svn/bin/svnplus
POSTCONFIG=/opt/mjc/svn/golab/src/mattermost-plugin-svn/conf/config.toml
# *************************************************************
# * This sets the arguments supplied by Subversion            *
# *************************************************************
REPOS=$1
REV=$2

# *************************************************************
# * Get Author and comment                                    *
# *************************************************************
# get comments
COMMENT=""
for cmt in `$SVNLOOK log -r $REV $REPOS`;
do
  COMMENT=$COMMENT"  "$cmt
done
# get author
AUTHOR=""
for atr in `$SVNLOOK author $REPOS -r $REV`;
do
  AUTHOR=$atr
done
# get file list
FILELIST=""
for fst in `$SVNLOOK changed $REPOS -r $REV `;
do
  FILELIST=$FILELIST"  "$fst
done

# *************************************************************
# * Hand it to commit                                       *
# *************************************************************
$POSTEXE -conf="$POSTCONFIG" -author="$AUTHOR" -comments="$COMMENT" -filelist="$FILELIST" -projectpath="$REPOS" -sendtype="" -rev="$REV"
exit 0
